/home/kasm920/binance1/logs/main.log
/home/kasm920/binance1/logs/system.log
/home/kasm920/binance1/logs/error.log
/home/kasm920/binance1/logs/trades.log
/home/kasm920/binance1/logs/orch/*.log {
    daily
    rotate 7
    missingok
    notifempty
    compress
    delaycompress
    copytruncate
    dateext
    dateformat -%Y%m%d
    maxsize 50M
}
